sequenceDiagram
    autonumber
    actor C as Cliente
    participant R as CustomerController
    participant U as CreateCustomerUseCaseImpl
    participant P as CustomerPersistencePort
    participant A as CustomerMongoAdapter
    participant M as MongoDB

    C->>R: POST /api/v1/customers
    R->>U: execute(customer)
    U->>P: existsByDocument(type, number)
    P->>A: existsByDocumentTypeAndDocumentNumber(...)
    A->>M: findOne
    M-->>A: resultado
    A-->>P: Boolean
    P-->>U: exists
    alt DNI ya registrado
        U-->>R: DuplicateCustomerException
        R-->>C: 409 Conflict
    else DNI nuevo
        U->>U: Customer.created(...)<br/>(profile=STANDARD, status=ACTIVE, hasOverdueDebit=false)
        U->>P: save(customer)
        P->>A: toDocument(customer)
        A->>M: save
        M-->>A: document
        A-->>P: document
        P-->>U: Customer
        U-->>R: Customer
        R-->>C: 201 Created
    end
