sequenceDiagram
    autonumber
    actor C as Cliente
    participant R as WalletController
    participant U as CreateWalletUseCase
    participant P as WalletPersistencePort
    participant A as WalletMongoAdapter
    participant M as MongoDB

    C->>R: POST /api/v1/wallets
    R->>U: execute(wallet)
    U->>P: existsByPhone(phoneNumber)
    P->>A: existsByPhoneNumber(...)
    A->>M: findOne
    M-->>A: resultado
    A-->>P: Boolean
    P-->>U: exists
    alt telefono ya registrado
        U-->>R: error
        R-->>C: 409 Conflict
    else ok
        U->>P: save(wallet)
        P->>A: toDocument(wallet)
        A->>M: save
        M-->>A: document
        A-->>P: document
        P-->>U: Wallet
        U-->>R: Wallet
        R-->>C: 201 Created
    end
