sequenceDiagram
    autonumber
    actor C as Cliente
    participant R as WalletController
    participant U as TransferWalletUseCase
    participant P as WalletPersistencePort
    participant M as MongoDB

    C->>R: POST /api/v1/wallets/transfers
    Note over R: body {sourcePhoneNumber, destinationPhoneNumber, amount}
    R->>U: execute(...)
    U->>P: findByPhone(sourcePhoneNumber)
    P->>M: findOne
    M-->>P: wallet origen
    P-->>U: Wallet origen
    U->>P: findByPhone(destinationPhoneNumber)
    P->>M: findOne
    M-->>P: wallet destino
    P-->>U: Wallet destino
    U->>U: origen.withdraw(amount) + destino.deposit(amount)
    Note over U: error si saldo insuficiente
    U->>P: save(origen) y save(destino)
    P->>M: save x2
    M-->>P: ok
    P-->>U: ok
    U-->>R: resultado
    R-->>C: 200 OK
